[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npx serve public"
  port = 3000
  targetPort = 3000

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/feed/:token"
  to = "/.netlify/functions/feed?token=:token"
  status = 200
